### ISSUE TITLE
Can't update node-fetch

### ISSUE THREAD

**Issue by cwchristerw** [warengroup/eximiabots-radiox#33]

**Comment by jimmywarting** [comment]
You can no longer use require to load node-fetch as it's now ESM only
you would have to switch to ESM also or use
```js
const fetch = (...args) => import('node-fetch').then(({default: fetch}) => fetch(...args));
```

**Comment by cwchristerw** [comment]
Then it will give this error in Javascript but typescript build doesnt fail.

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/src/app/node_modules/node-fetch/src/index.js from /usr/src/app/build/client/events/ready.js not supported.
Instead change the require of index.js in /usr/src/app/build/client/events/ready.js to a dynamic import() which is available in all CommonJS modules.
```

**Comment by cwchristerw** [comment]
I wrote this earlier in Discord:

>I will put this into my Typescript file
const fetch = (...args) => import('node-fetch').then(({default: fetch}) => fetch(...args));

>but it will be builded into this
const fetch = (...args) => Promise.resolve().then(() => __importStar(require('node-fetch'))).then(({ default: fetch }) => fetch(...args));

>This causes ERR_REQUIRE_ESM, but if I manually edit file in build folder to const fetch = (...args) => import('node-fetch').then(({default: fetch}) => fetch(...args)); then it will work but give only 
(node:18) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

Havent tested yet those possible solutions

**Comment by cwchristerw** [comment]
https://github.com/node-fetch/node-fetch/issues/1263
https://github.com/microsoft/TypeScript/issues/43329

**Comment by cwchristerw** [comment]
https://github.com/warengroup/eximiabots-radiox/blob/ac323a541072dd9d2893bb523bd4c130ce848891/src/client/events/ready.js#L2-L3

https://github.com/warengroup/eximiabots-radiox/blob/ac323a541072dd9d2893bb523bd4c130ce848891/src/client/commands/maintenance.js#L2-L3

@jimmywarting This is temporary fix to my issue

**Comment by cwchristerw** [comment]
Is there a way to hide experimental feature warning @jimmywarting 
```
(node:18) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by jimmywarting** [comment]
It is possible to run node with --no-warning flag
Also, if globalThis.ReadableStream is defined then it won't load stream/web that gives you the error

**Comment by cwchristerw** [comment]
Is this safe way to import module if it works, can I push this to production bot when its time to release version 0.3.10.

**Comment by cwchristerw** [comment]
I have planned #23 & #24, and they both require fetch to work properly :smile:

**Comment by jimmywarting** [comment]
Grate idea about constructing a new function that don't get transformed 

Will start recommend it in node-fetch also

**Comment by cwchristerw** [comment]
Nice @jimmywarting :smile:

**Comment by cwchristerw** [comment]
I just looked for solution in https://github.com/microsoft/TypeScript/issues/43329 and saw that there is example _importDynamic and then decided try it in combined with earlier https://github.com/warengroup/eximiabots-radiox/issues/33#issuecomment-910538148

**Comment by Masterxilo** [comment]
Biggest headache of the day.

For anyone who does not have time to figure out how to get ESM to work with typescript and ts-node or whatever and just wants a browser-like fetch function fast, now, downgrade to node-fetch 2.x.x:
```
  "devDependencies": {
    "@types/node": "^16.10.3",
    "@types/node-fetch": "^2.0.0",
    "ts-node": "^10.2.1",
    "typescript": "^4.4.4"
  },
  "dependencies": {
    "node-fetch": "^2.0.0"
  }
```

and just import as

```
import fetch from 'node-fetch';
```
